# Generated by Django 3.1.6 on 2021-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=50, unique=True)),
                ('movie_status', models.IntegerField(choices=[(0, 'Unwatched'), (1, 'Watching'), (2, 'Watched')], default=0)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='WebSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=50, unique=True)),
                ('movie_status', models.IntegerField(choices=[(0, 'Unwatched'), (1, 'Watching'), (2, 'Watched')], default=0)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
    ]
