# Generated by Django 3.1.6 on 2021-02-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0002_auto_20210219_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_status',
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='movie_status',
        ),
    ]
